sudo: false
language: ruby
notifications:
  email: false
rvm:
  - 2.3

before_install:
   gem install bundler -v 1.16.1 && (gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true)
script:
  - bundle exec rake spec
